baseURL = 'https://paperpause.app/'
languageCode = 'en-us'
title = 'PaperPause'
theme = 'visual-sanctuary-theme'

[params]
  description = "Discover the best free printable coloring pages for adults and kids. High-quality animals, mandalas, and more."

# GA4 Integration
googleAnalytics = "G-R0NHTPYWFY"

[taxonomies]
  category = "categories"  # Silo (Animals)
  series = "collections"   # Sub-Silo (Cats)




[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30

[module]

  [module.hugoVersion]
    extended = true
    min = "0.110.0"

[outputFormats]
  [outputFormats.SECTION_SITEMAP]
    mediaType = "application/xml"
    baseName = "sitemap"
    isPlainText = false
    isHTML = false

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
  section = ["HTML", "RSS", "SECTION_SITEMAP"]
