name = "paperpause"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "visual-sanctuary-assets"
preview_bucket_name = "visual-sanctuary-assets-preview"
